apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
  labels:
    app: blockchain
spec:
  replicas: 28
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: blockchain
      containers:
      - name: blockchain
        image: 576651666672.dkr.ecr.us-east-1.amazonaws.com/ccfall2022:blockchainArm
        ports:
        - containerPort: 8080


# ---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: qrcode-scaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: qrcode
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 70