apiVersion: apps/v1
kind: Deployment
metadata:
  name: twitter
  labels:
    app: twitter
spec:
  replicas: 28
  selector:
    matchLabels:
      app: twitter
  template:
    metadata:
      labels:
        app: twitter
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: twitter
      containers:
      - name: twitter
        image: 576651666672.dkr.ecr.us-east-1.amazonaws.com/ccfall2022:twitterRDS-ARM
        ports:
        - containerPort: 8080
        envFrom:
          - configMapRef:
              name: twitter-config



# ---

# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: qrcode-scaling
#   namespace: default
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: qrcode
#   minReplicas: 1
#   maxReplicas: 10
#   targetCPUUtilizationPercentage: 70